version: '3.6'
services:
  app:
    image: "golang"
    depends_on:
      - "db"
    network_mode: bridge
    build:
      context: .
      args: []
    environment:
      CONNSTR: "root:supersecurepassword@tcp(docker.for.mac.localhost:3306)/familytree"
    ports:
      - "8080:8080"
    command: "sh -c 'sleep 5 ; /go/src/github.com/x1um1n/family-tree/family-tree'"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "familytree"
      MYSQL_ROOT_PASSWORD: "supersecurepassword"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - family-tree-db:/var/lib/mysql
volumes:
  family-tree-db:
